# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G1', '0003_auto_20170327_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de Inscricao')),
            ],
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='tipoInscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='G1.TipoInscricao'),
        ),
    ]
