# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G1', '0004_auto_20170327_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='G1.Evento'),
            preserve_default=False,
        ),
    ]
